### ISSUE TITLE
Bridge to Home Assistant

### ISSUE THREAD

**Issue by wsw70** [diyhue/Devices#1]
The documentation mentions "Home Assistant" as one of the supported devices.

Is it possible to use `diyhue` as a bridge to `emulated_hue` on Home Assistant? That would be useful in case where a Logitech Harmony Hub is on a network different from Home Assistant, and would forward the requests.

If that would be the case - what is the right configuration?

**Comment by ghost** [comment]
I'm a bit confused as to what you're trying to achieve. You can consider diyHue to be a real Hue bridge, so anything you can do with Home Assistant and a real Hue bridge you should be able to do with diyHue with the same config.

As for using the emulated_hue component with diyHue, my understanding was that it exposed devices in HomeAssistant to Alexa and Google Home for use with voice assistants. I'm not sure how this ties in with your use case. Can you explain further?

**Comment by Nikfinn99** [comment]
Right now, Homeassistant can only activate themes configured in the diyhue bridge. This is the only implemented integration. But currently this function is broken and does not work. 
I would suggest to use NodeRED to integrate the emulated hue bridge into whatever system you have.
NodeRED has a plugin called "node-red-contrib-huemagic". This plugin has a good implementation for using the Hue API and all suported devices.
