### ISSUE TITLE
Use Philip switch with emulated Hue

### ISSUE THREAD

**Issue by thenamanpat** [diyhue/Devices#2]
The docs mention ways to create your own switch and motion sensor that work with the emulated Hue.
https://diyhue.readthedocs.io/en/latest/AddFuncts/sensors.html#switches

I was unable to find documentation for connecting an actual Hue Switch to the emulated Hue. "Accessory setup" on the Hue App is unable to find this switch. It tested the switch against an actual Hue and the App was able to set it up.

Any guidance would be appreciated. I tried restarting the docker container emulating the Pi in case the config file needed to get updated.

**Comment by Mevel** [comment]
Original hue switch use zigbee radio protocol. You need a special receiver to make it work. The conbee or raspbee dongle work good. Once you have the extra hardware, you can add original products to diyhue

**Comment by jorisvanr** [comment]
I use original Hue Switches with a raspbee module. More on that [here](https://diyhue.readthedocs.io/en/latest/lights/raspbee.html). Unfortunately you can't connect them to the original bridge and import them like the lights.

**Comment by ghost** [comment]
Closing as this issue seems to have been answered. If more support is required, please reopen this issue.
