### ISSUE TITLE
Cant connect Hue Dimmer Switch to Emulator

### ISSUE THREAD

**Issue by maskedfighter** [diyhue/Devices#3]
Hello!

First of all, i appreciate your work on this project. I have some issues connecting deconz to the emulator. Whenever I go to the phoscon web-app i first connect the dimmer switch, then remove it. Afterwards i go to gateway-settings and click 'authenticate app'. When i then browse to 'my_ip/deconz' i get an empty response. At this stage, i am able to visit the main emulator-page, but when i force a restart via ssh, i cant get any access to the webpage anymore (error_connection_refused). Phoscon webpage still reachable, so is ssh. This is really frustrating, cause, for now, the only way to get it working again is to freshly install the system onto the card. 

Anyone here with the same issues? Any help appreciated :)

**Comment by Mevel** [comment]
Did you change the websocket and web page port of deconz as described in the diyhue documentation?

**Comment by maskedfighter** [comment]
yep. i just tried it again following the wiki step by step (wiki is outdated btw...), but since it isn´t explained very well how to connect deconz to emulator, its a little bit frustrating trying it getting to work. 
Can someone explain how to connect deconz (and my philips dimmer switch) to the diy-bridge? cause for now, i don´t see how to do it (as the wiki is outdated for a while now... new phoscon webinterface...).

**Comment by maskedfighter** [comment]
What i have done so far:
-installed latest deconz.deb
-started phoscon webapp and added dimmer switch, then removed him
-in 'options' -> 'gateway' -> 'authenticate app' allowing it 3rd party apps to join the gateway
- after that i went to http://my_ip/deconz
- browser shows me that there was nothing that the server was able to get back (error_empty_page)
-restart of server via ssh
- after that restart, i am unable to connect via webbrowser as it says 'error_connection_refused'.

Don´t know what to do anymore. :/
